version: '3'
services:
  app:
    image: "laserstack/app:${PHP_VERSION}"
    # build:
    #   context: ./docker/app
    #   dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    hostname: laser
    environment:
      LASER: 1
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    tty: true
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - ${PROJECTS_DIRECTORY}:/var/www:cached
      - ./config/supervisord.${PHP_VERSION}/supervisord.conf:/etc/supervisord.conf:cached
      - ./config/nginx:/etc/nginx/http.d:cached
      - ./config/php/php.ini:/etc/php81/php.ini:cached
      - ./config/php/php-fpm.conf:/etc/php81/php-fpm.conf:cached
      - ./config/php/php-fpm.d:/etc/php81/php-fpm.d:cached
    networks:
      - laser

networks:
  laser:
    driver: bridge
