version: '3'
services:
  app:
    image: "laserstack/app:${PHP_VERSION}"
    # build:
    #   context: ./docker/app
    #   dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    hostname: laser
    environment:
      LASER: 1
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    tty: true
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - ./config/supervisord/supervisord.conf:/etc/supervisord.conf:cached
      - ./config/nginx:/etc/nginx/conf.d:cached
      - ${PROJECTS_DIRECTORY}:/var/www:cached
    networks:
      - laser

networks:
  laser:
    driver: bridge
