version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    environment:
      LASER: 1
    tty: true
    working_dir: /var/www
    volumes:
      - ${PROJECTS_DIRECTORY}:/var/www:cached
    networks:
      - laser
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      LASER: 1
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - dbdata:/var/lib/mysql:delegated
    networks:
      - laser
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      LASER: 1

volumes:
  dbdata:
    driver: local

networks:
  laser:
    driver: bridge
